### ISSUE TITLE
stabilizer.cpp fails to compile with opencv < 3.2

### ISSUE THREAD

**Issue by uartie** [01org/libxcam#475]
```
In file included from stabilizer.cpp:21:0:
stabilizer.h:31:21: error: ‘videostab’ is not a namespace-name
 using namespace cv::videostab;
                     ^~~~~~~~~
```
cv::videostab namespace is defined in <opencv2/videostab.hpp>.  In opencv version 3.2+, this header is automatically included from <opencv2/opencv.hpp>.  However, prior to version 3.2, files must explicitly include <opencv2/videostab.hpp>
