### PR TITLE
libdvs: include opencv2/videostab.hpp

### LINKED ISSUE #475: stabilizer.cpp fails to compile with opencv < 3.2
```
In file included from stabilizer.cpp:21:0:
stabilizer.h:31:21: error: ‘videostab’ is not a namespace-name
 using namespace cv::videostab;
                     ^~~~~~~~~
```
cv::videostab namespace is defined in <opencv2/videostab.hpp>.  In opencv version 3.2+, this header is automatically included from <opencv2/opencv.hpp>.  However, prior to version 3.2, files must explicitly include <opencv2/videostab.hpp>

### PR DESCRIPTION
**Pull request by uartie**
The opencv2/videostab.hpp header is not indirectly included
via the opencv2/opencv.hpp header until OpenCV version 3.2+.

Thus, explicitly include opencv2/videostab.hpp so libdvs can
compile with OpenCV version 3.1.

Fixes #475

Signed-off-by: U. Artie Eoff <ullysses.a.eoff@intel.com>

### CODE REVIEW

**Comment by windyuan** [comment]
merged. thank you for the fix:)
